In [1]:
import pandas as pd
import numpy as np

In [3]:
AK4 = pd.read_csv("data_expe/AK4_data.csv")
AK4

,anecdotes,fichier,anecdotes_reco,boucle_tâche.thisRepN,boucle_tâche.thisTrialN,boucle_tâche.thisN,boucle_tâche.thisIndex,boucle_reco.thisRepN,boucle_reco.thisTrialN,boucle_reco.thisN,...,mouse_reco.clicked_name,text_2.started,end.started,participant,session,date,expName,psychopyVersion,frameRate,Unnamed: 65
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,AK4,1.0,2023-03-17_12h01.51.012,Expérimentation1_SOLO,2022.2.5,60.031721,NaN
1,La république dominicaine est le seul pays qui...,NOMS,La république dominicaine est le seul pays qui...,0.0,0.0,0.0,15.0,NaN,NaN,NaN,...,NaN,NaN,NaN,AK4,1.0,2023-03-17_12h01.51.012,Expérimentation1_SOLO,2022.2.5,60.031721,NaN
2,La navette Spatiale Columbia s’est désintégrée...,DONNEES,La navette Spatiale Columbia s’est désintégrée...,0.0,1.0,1.0,9.0,NaN,NaN,NaN,...,NaN,NaN,NaN,AK4,1.0,2023-03-17_12h01.51.012,Expérimentation1_SOLO,2022.2.5,60.031721,NaN
3,Le Groenland est l’île la plus grande du monde...,FAITS,Le Groenland est l’île la plus grande du monde...,0.0,2.0,2.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,AK4,1.0,2023-03-17_12h01.51.012,Expérimentation1_SOLO,2022.2.5,60.031721,NaN
4,Le cœur d’une crevette est dans sa tête,POINTS,Le cœur d’une crevette est dans sa tête,0.0,3.0,3.0,28.0,NaN,NaN,NaN,...,NaN,NaN,NaN,AK4,1.0,2023-03-17_12h01.51.012,Expérimentation1_SOLO,2022.2.5,60.031721,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Les frites sont originaires de France et non d...,INFOS,Les frites sont originaires de France et non d...,NaN,NaN,NaN,NaN,0.0,28.0,28.0,...,['validation_reco'],NaN,NaN,AK4,1.0,2023-03-17_12h01.51.012,Expérimentation1_SOLO,2022.2.5,60.031721,NaN
64,La pyramide de Gizé est la seule des 7 merveil...,ITEMS,La pyramide de Gizé est la seule des 7 merveil...,NaN,NaN,NaN,NaN,0.0,29.0,29.0,...,['validation_reco'],NaN,NaN,AK4,1.0,2023-03-17_12h01.51.012,Expérimentation1_SOLO,2022.2.5,60.031721,NaN
65,La plus longue composition classique prendrait...,POINTS,La plus longue composition classique prendrait...,NaN,NaN,NaN,NaN,0.0,30.0,30.0,...,['validation_reco'],NaN,NaN,AK4,1.0,2023-03-17_12h01.51.012,Expérimentation1_SOLO,2022.2.5,60.031721,NaN
66,La Corée du Nord a annoncé avoir conduit un te...,ITEMS,La Corée du Nord a annoncé avoir conduit un te...,NaN,NaN,NaN,NaN,0.0,31.0,31.0,...,['validation_reco'],NaN,NaN,AK4,1.0,2023-03-17_12h01.51.012,Expérimentation1_SOLO,2022.2.5,60.031721,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1817.441857,1817.441857,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
AK4 = AK4[['anecdotes','fichier','tache_text.text','anecdotes_reco','reco_text.text']]

In [12]:
AK4_RECO = AK4[['anecdotes_reco', 'fichier', 'reco_text.text']].loc[35:66]
AK4_RECO = AK4_RECO.reset_index()
AK4_RECO['reco_text.text'] = AK4_RECO['reco_text.text'].str.upper()
AK4_RECO['reco_text.text'] = AK4_RECO['reco_text.text'].replace(
    'DONNÉES',
    'DONNEES').replace('FAIT', 'FAITS').replace('DONNEE', 'DONNEES').replace(
        'POINT',
        'POINTS').replace('ITEM', 'ITEMS').replace('NOM', 'NOMS').replace(
            'INFO', 'INFOS').replace('DONNÉE', 'DONNEES').replace(
                'DONNÉS', 'DONNEES').replace('DONNÉ', 'DONNEES').replace(
                    'POINT\n', 'POINTS').replace('FAIT\n', 'FAITS')
AK4_RECO

,index,anecdotes_reco,fichier,reco_text.text
0,35,L’indicatif téléphonique international de l’An...,INFOS,POINTS
1,36,La carte de visite d’Al Capone indiquait qu’il...,INFOS,NOMS
2,37,On peut reproduire une clé grâce au son qu’ell...,POINTS,NaN
3,38,Une personne perdra environ 18 kilos de peau d...,POINTS,POINTS
4,39,"Seulement 2 pays touchent 3 océans, les Etats-...",FAITS,NOMS
5,40,La navette Spatiale Columbia s’est désintégrée...,DONNEES,INFOS
6,41,La république dominicaine est le seul pays qui...,NOMS,FAITS
7,42,Les séparatistes Tchéchènes du Sud de la Russi...,POINTS,INFOS
8,43,L’Himalaya continue de grandir en raison des c...,ITEMS,DONNEES
9,44,Le tsunami dévastateur en Asie s’est produit e...,FAITS,INFOS
10,45,Le Groenland est l’île la plus grande du monde...,FAITS,DONEE
11,46,L’écriture chinoise comprend plus de 40 000 ca...,NOMS,NOMS
12,47,Il y a eu 25 présidents Français,DONNEES,FAITS
13,48,L’océan Atlantique est plus salé que l’océan P...,NOMS,NOMS
14,49,La raie manta peut atteindre 9 mètres de long ...,INFOS,INFOS
15,50,Les oiseaux bleus ne peuvent pas voir la coule...,FAITS,FAITS
16,51,"Tout comme l’empreinte digitale, le cœur est p...",NOMS,POINTS
17,52,Une personne brule plus de calories quand il d...,ITEMS,INFOS
18,53,Les concerts Live 8 ont pris place dans les pa...,NOMS,NOMS
19,54,Les élastiques sont plus longs quand ils sont ...,INFOS,POINTS
20,55,Un attentat terroriste a eu lieu dans les métr...,DONNEES,NaN
21,56,L’Europe est le seul continent sans désert,DONNEES,DONNEES
22,57,La cacahuète est l’un des ingrédients de la dy...,POINTS,POINTS
23,58,Le cœur d’une crevette est dans sa tête,POINTS,INFOS
24,59,Une vache produit environ 200 000 bouteilles d...,FAITS,FAITS
25,60,Les ongles incarnés sont héréditaires,DONNEES,FAITS
26,61,L’œil d’une autruche est plus gros que son cer...,ITEMS,DONNEES
27,62,Il y a en moyenne 178 graines de sésames sur l...,NOMS,NOMS
28,63,Les frites sont originaires de France et non d...,INFOS,INFOS
29,64,La pyramide de Gizé est la seule des 7 merveil...,ITEMS,INFOS
30,65,La plus longue composition classique prendrait...,POINTS,POINTS
31,66,La Corée du Nord a annoncé avoir conduit un te...,ITEMS,NOMS

In [9]:
Grep = AK4_RECO['fichier']==AK4_RECO['reco_text.text']
Grep

35    False
36    False
37    False
38     True
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46     True
47    False
48     True
49     True
50     True
51    False
52    False
53     True
54    False
55    False
56     True
57     True
58    False
59     True
60    False
61    False
62     True
63     True
64    False
65     True
66    False
dtype: bool

In [10]:
Grep.value_counts()

False    20
True     12
dtype: int64